title: "Computational Economic Notes"
email: zedtaha@gmail.com
description: "An open-access journal for economic research and computing"
baseurl: "/Computational-Economic-Notes"
url: "https://compeconote.github.io"

theme: minima
markdown: kramdown

permalink: pretty

# Build settings
safe: true
include:
  - _pages
exclude:
  - .github
  - Gemfile
  - Gemfile.lock
