title: "Computational Economic Notes"
email: zedtaha@gmail.com
description: "A scientific journal website"
baseurl: "" 
url: "https://tahazaghdoudi.github.io"  

theme: minima

markdown: kramdown
plugins:
  - jekyll-feed

# Collections configuration
collections:
  papers:
    output: true
    permalink: /papers/:path/
  submissions:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "papers"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "submissions"
    values:
      layout: "default"
